### ISSUE TITLE
monika can't read my file

### ISSUE THREAD

**Issue by felskyy** [Friends-of-Monika/spritepack-archive#1]
When i send her a spritepack gift from the game website everything is ok but when i do the same from this website monika says that she can't read the file. When I copy mod assets folder from the game website spritepack to game folder it always says if I want to replace some files but when I copy mod assets folder from this website and every other website on internet to game folder, it never says if I want to replace any files, I think that matters. Plz help ://

**Comment by dreamscached** [comment]
Make sure you install `mod_assets` to `game` properly, make sure you give her exactly the .gift files that are in the packages.

**Comment by felskyy** [comment]
> Make sure you install `mod_assets` to `game` properly, make sure you give her exactly the .gift files that are in the packages.

I've tried many times but it still doesn't work. It works only when I do it with a spritepack from the official website "monika after story"

**Comment by dreamscached** [comment]
I'm sorry, but the process of installing these spritepacks isn't anything different from installing official ones. Were you by any chance getting them using 'code' button on the main page?
